name: reto
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http:
  meta: ^1.1.8
  equatable: ^1.2.3
  dartz: ^0.9.1
  json_serializable: ^3.3.0
  json_annotation: ^3.0.1
  rxdart: ^0.24.1
  kt_dart: ^0.7.0+1
  freezed_annotation: ^0.11.0
  get_it: ^4.0.4
  injectable: ^1.0.2
  shared_preferences: ^0.5.8
  flutter_bloc: ^6.0.1
  auto_route: ^0.6.6
  flushbar: ^1.10.4
  moor_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  build_runner: ^1.10.0
  freezed: ^0.11.4
  auto_route_generator: ^0.6.6
  injectable_generator: ^1.0.2
  moor_generator:
flutter:
  uses-material-design: true
